// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEDiGr0pF5y3KnQoNptEv8DlHUmpgMmGs',
    appId: '1:196604458762:web:0dc6c830c4b440e96fecf3',
    messagingSenderId: '196604458762',
    projectId: 'thirsttea-d3589',
    authDomain: 'thirsttea-d3589.firebaseapp.com',
    storageBucket: 'thirsttea-d3589.firebasestorage.app',
    measurementId: 'G-GC7R27SB8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtfVyHMsohVDgUVWeRi-Ban3H-xnrvAXM',
    appId: '1:196604458762:android:d6f67ffe8fa257a26fecf3',
    messagingSenderId: '196604458762',
    projectId: 'thirsttea-d3589',
    storageBucket: 'thirsttea-d3589.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdRnHWHUteRgjUJqFC9T-eiunyduGIIfA',
    appId: '1:196604458762:ios:fd1aeffb41ff4ba96fecf3',
    messagingSenderId: '196604458762',
    projectId: 'thirsttea-d3589',
    storageBucket: 'thirsttea-d3589.firebasestorage.app',
    iosBundleId: 'com.example.thirstTea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdRnHWHUteRgjUJqFC9T-eiunyduGIIfA',
    appId: '1:196604458762:ios:fd1aeffb41ff4ba96fecf3',
    messagingSenderId: '196604458762',
    projectId: 'thirsttea-d3589',
    storageBucket: 'thirsttea-d3589.firebasestorage.app',
    iosBundleId: 'com.example.thirstTea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEDiGr0pF5y3KnQoNptEv8DlHUmpgMmGs',
    appId: '1:196604458762:web:19eca2a962f4b6d56fecf3',
    messagingSenderId: '196604458762',
    projectId: 'thirsttea-d3589',
    authDomain: 'thirsttea-d3589.firebaseapp.com',
    storageBucket: 'thirsttea-d3589.firebasestorage.app',
    measurementId: 'G-0QKEQXW2WN',
  );
}
